Classes/Sitegeist/Monocle/TypoScript/InlineTemplateImplementation.php, Resources/Private/TypoScript/Prototypes/InlineTemplate.ts2
The inline template allows to use small fluid templates directly in ts2.
Usage:
```
prototype(Vendor.Site:ExampleInlineTemplate) < prototype(Sitegeist.Monocle:InlineTemplate){
variable = TYPO3.TypoScript:Value {
value = 'example string'
}
template = '<div>{variable}</div>'
}
```
=> FEATURE: Inline Template TypoScriptObject

Classes/Sitegeist/Monocle/Fusion/FusionService.php, README.md
- The default `path` is now the component name (without VendorNamespace)
- The default `title` default is now the component name splittet reversed and glued with spaces again
=> FEATURE: Make `title` and `path` annotations optional and infer meaningful defaults

Configuration/Routes.yaml
This fixes an annoying bug, through which flow couldn't figure out the correct route to redirect to after login. So, when your session timed out, you got to see the Neos login screen after which you got redirected to a 404 page.
By adding `@format` to the default values, this redirect works now.
=> BUGFIX: Add default formats to monocle routes

Classes/Sitegeist/Monocle/Command/StyleguideCommandController.php, Classes/Sitegeist/Monocle/Controller/ApiController.php, Classes/Sitegeist/Monocle/Controller/PreviewController.php, Classes/Sitegeist/Monocle/Service/DummyControllerContextTrait.php, Classes/Sitegeist/Monocle/Service/PackageKeyTrait.php
This adds a `styleguide:render` flow command.
Usage:
```sh
./flow styleguide:render MyAwesome.Package:MyAwesome.Component
```
The result will be the rendered HTML of the given component. This functionality is required to run JS-based unit tests against components.
=> FEATURE: Add styleguide:render CLI command

Resources/Private/JavaScript/containers/styleguide/header/toolbox/breakpoint-selector/breakpoint-list/breakpoint/index.js, Resources/Private/JavaScript/containers/styleguide/header/toolbox/breakpoint-selector/breakpoint-list/breakpoint/style.css, Resources/Private/JavaScript/containers/styleguide/header/toolbox/breakpoint-selector/breakpoint-list/index.js, Resources/Private/JavaScript/containers/styleguide/header/toolbox/breakpoint-selector/breakpoint-list/style.css
Makes more sense, right? :)
Also, this PR filters breakpoints that have been deactivated via yaml:
```yaml
Sitegeist:
Monocle:
ui:
viewportPresets:
l: ~
```
Currently, those entries still show up in the UI.
=> FEATURE: Display viewport dimensions instead of view port name

Classes/Sitegeist/Monocle/Fusion/ReverseFusionParser.php
This change makes `in_array()` comparisons in the `ReverseFusionParser`
use strict comparison. That fixes #71, which is caused by type casting, as
`in_array(0, ['something'])` evaluates to `true`, since `(string)'something'`
is `0`.
=> BUGFIX: Fix reverse parsing of 0 index keys

Configuration/Development/Policy.yaml, Configuration/Policy.yaml, README.md
This allows designers to work with the styleguide without any authentication or database
connection by directly using the url. http://127.0.0.1:8081/monocle/preview/module/
=> TASK: Make the monocle module publicly accessible in development context

Classes/Sitegeist/Monocle/FusionObjects/PreviewPrototypeImplementation.php, Resources/Private/Fusion/Prototypes/Preview/Prototype.fusion
Changes `Sitegeist.Monocle:Preview.Prototype`'s `props` and `locales`
fusion values to be initialized as array to be correctly processed in
Monocle's `FusionView` implementation.
Otherwise overriding a component's properties from within another component's styleguide definition would require specifying `props` as an array instead of just writing
```
prototype(Vendor.Site:Container) {
@styleguide{
props.content = Sitegeist.Monocle:Preview.Prototype {
prototypeName = 'Vendor.Site:Item'
props {
foo = 'bar'
}
}
}
...
}
```
=> BUGFIX: Fix `Preview.Prototype` `props` and `locales` fusion value types

Classes/Sitegeist/Monocle/Aspects/FusionCachingAspect.php, Classes/Sitegeist/Monocle/Package.php, Configuration/Caches.yaml, Configuration/Objects.yaml, Configuration/Settings.yaml, README.md
Monocle will cache the fusion code for every site package. To invalidate this cache
the the Fusion directories of all packages are monitored and changes trigger the flushing
of the fusion-cache.
The setting `Sitegeist.Monocle.fusion.enableObjectTreeCache` enables the caching in
Monocle by default.
=> FEATURE: Fusion Object Tree Caching

Classes/Sitegeist/Monocle/FusionObjects/DataUriImplementation.php, Classes/Sitegeist/Monocle/Package.php, README.md, Resources/Private/Fusion/Prototypes/DataUri/DataUri.fusion, Resources/Private/Fusion/Prototypes/DataUri/Json.fusion, Resources/Private/Fusion/Prototypes/DataUri/Text.fusion
Those prototypes are useful to simulate api endpoints in the styleguide
- `Sitegeist.Monocle:DataUri`: Generic data uri implementation that expects `type` and `content` as string
- `Sitegeist.Monocle:DataUri.Json`: And endpoint-mock with media-type `application/json` that will pass `content` trough Json.stringify
- `Sitegeist.Monocle:DataUri.Text`: And endpoint-mock with media-type `text/plain`
=> FEATURE Add data-uri prototypes

Classes/Sitegeist/Monocle/Controller/MockController.php, Configuration/Development/Policy.yaml, Configuration/Policy.yaml, Configuration/Routes.yaml, README.md, Resources/Private/Fusion/Prototypes/DataUri/DataUri.fusion, Resources/Private/Fusion/Prototypes/DataUri/Json.fusion, Resources/Private/Fusion/Prototypes/DataUri/Text.fusion, Resources/Private/Fusion/Prototypes/MirrorUri/Json.fusion, Resources/Private/Fusion/Prototypes/MirrorUri/MirrorUri.fusion, Resources/Private/Fusion/Prototypes/MirrorUri/Text.fusion
The fusion prototype `Sitegeist.Monocle:MirrorUri` creates an uri to an monocle-endpoint that returns the passed content with the given type
```
endpointUrl = Sitegeist.Monocle:MirrorUri {
content = '{"hello":"world"}'
type = 'application/json'
}
```
For convenience special prototypes for json and text exist aswell:
- `Sitegeist.Monocle:MirrorUri.Json`: And endpoint-mock with media-type `application/json` that accepts RawArray data
- `Sitegeist.Monocle:MirrorUri.Text`: And endpoint-mock with media-type `text/plain`
=> FEATURE: Sitegeist.Monocle:MirrorUri endpoint

Classes/Sitegeist/Monocle/Controller/MockController.php, Configuration/Policy.yaml, Configuration/Settings.yaml, README.md, Resources/Private/Fusion/Prototypes/StaticUri/StaticUri.fusion
The prototype creates an URI that will return the content of the file and the contentType for the given key.
```
endpointUrl = Sitegeist.Monocle:StaticUri {
key = 'example'
}
```
The path and content type for each key are configured via Settings:
```yaml
Sitegeist:
Monocle:
uriMock:
static:
example:
path: 'resource://Vendor.Package/Private/Json/example.json'
contentType: 'application/json'
```
=> FEATURE: Add Sitegeist.Monocle:StaticUri prototype

Classes/Sitegeist/Monocle/Command/StyleguideCommandController.php
This adds `propSet`, `props` and `locales` parameters to `./flow styleguide:render`.  `props` and `locales` can be passed as JSON:
```sh
./flow styleguide:render Vendor.Site:Component.Atom.Container --props '{"content":"Foo"}'
```
Also, fixes #76
=> FEATURE: Enhance cli rendering

Classes/FusionObjects/CanRenderImplementation.php, Resources/Private/Fusion/Prototypes/CanRender/CanRender.fusion, Resources/Private/Fusion/Prototypes/Preview/Prototype.fusion
Defining whole props and propSets as Expressions or Fusion prototypes allows to
centralize the fixtures and even extract them into separate json files.
When props or propSets cannot be evaluated directly the keys below are evaluated
as RawArray as before so this change is a non breaking feature.
```
prototype (Vendor.Site:Example) < prototype(Neos.Fusion:Component) {
@styleguide {
propSets {
fromEelExpression = ${{title: 'hello world'}}
fromFusionPrototype = Vendor.Site:Example.Fixtures
fromJsonFile = ${Json.parse(File.readFile('_path_to_fixctures.json'), true)}	}
}
}
```
=> FEATURE: Allow defining of whole props and propSets as Fusion prototypes or expressions

Classes/Controller/ApiController.php, Configuration/Settings.yaml, README.md
Adds a new configuration option `alwaysShowPrototypes` that allows
for including prototypes selectively even though they match a
configured `hiddenPrototypeNamePatterns`:
```yaml
Sitegeist:
Monocle:
hiddenPrototypeNamePatterns:
- 'Vendor.Components:*'
alwaysShowPrototypes:
- 'Vendor.Components:Components.Atom.SomeAtom'
- 'Vendor.Components:Components.Molecule.SomeMolecule'
```
Resolves: #89
=> FEATURE: Prototype Whitelist

package.json, postcss.config.js, yarn.lock
The Javascript build gets 3 times smaller and in the CSS, the empty `:root {}` gets removed
=> FEATURE: Minimize public sources on build

README.md, Resources/Private/Fusion/Prototypes/Preview/Page.fusion
Often components have to be rendered in the styleguide inside another component. In this case a `container`
can be defined in the styleguide annotation. The container is the applied as processor to the uppermost prototype.
```
prototype(Vendor.Site:ExampleComponent) < prototype(Neos.Fusion:Component) {
@styleguide {
container = Vendor.Site:ExampleContainer
}
renderer = afx`
<h1>Hello World</h1>
`
}
```
The `container` prototype has to accept the prop `content` that will contain the rendered prototype.
```
prototype(Vendor.Site:ExampleContainer) < prototype(Neos.Fusion:Component) {
content = null
renderer = afx`
<div class="container">{props.content}</div>
`
}
```
*Please note that containers are only rendered for the uppermost prototype that is rendered in the styleguide. For all other …
=> FEATURE: Prototypes can define `@styleguide.container` for preview

Classes/Fusion/FusionService.php, Classes/Service/PackageKeyTrait.php, Configuration/Settings.yaml, README.md
The `packages` configuration can now be used to configure non-site packages for previewing in the styleguide.
When a prototyope of a non-site package is rendered Monocle will only load the Root.fusion of this specific package and the Monocle Root.fusion. Every other fusion including the default fusion has to be included explicitly. This mimics the behavior of the classic FusionView that is used for FusionRendering of Flow Controller Actions.
```YAML
Sitegeist:
Monocle:
packages:
#add a key to the package list without package specific configuration
'Vendor.Example': {}
```
In addition a smarter and configurable way to determine the defaultPackageKey was added.
If a domain can be identified from the current request monocle will use this to determine the initial sitePackage.
If that does not …
=> FEATURE: Preview for non site packages

Classes/Domain/Fusion/PrototypeRepository.php
In recent versions the API endpoint `prototypeDetails` can fail if the Prototype has a `@cache` declared. The reason is, that the fusion runtime has the content cache enabled by default. As the cache is evaluated, `Neos.Fusion:GlobalCacheIdentifiers` is used for the `entryIdentifier` which uses `documentNode` to add the `workspaceChain` like this:  
```
workspaceChain = ${documentNode.context.workspace.name + ',' + Array.join(Array.keys(documentNode.context.workspace.baseWorkspaces), ',')}
```
Since no `documentNode` is set for rendering the Prototype, `Array.keys` fails with an exception because it expects an array instead of `null`.
With this PR, the content cache is disabled in the `PrototypeRepository` and fixes the issue.
=> BUGFIX: PrototypeRepository disables content cache in FusionRuntime

README.md, Resources/Private/Fusion/Prototypes/Preview/Page.fusion
The containers never really worked via defining the prop content. This was a wrong assumption as i always had `content = ${value}` in my containers anyways.
This change describes the working way and removes the non working lines that caused confusion.
=> DOCS: Remove non working element.content from preview containers and adjust docs

Classes/Domain/PrototypeDetails/Props/EditorFactory.php, README.md
Adds a new `@styleguide` option `hidePropsInInspector` that allows to
hide specified props in the Inspector.
Resolves: #162
=> FEATURE: Allow props to be removed from Inspector

Classes/Controller/ApiController.php, Classes/Domain/PrototypeDetails/PropSets/PropSetCollection.php, Classes/Domain/PrototypeDetails/Props/PropValue.php, Classes/Domain/PrototypeDetails/PrototypeDetailsFactory.php, Classes/Domain/PrototypeDetails/PrototypeDetailsFactoryInterface.php, Classes/Domain/PrototypeDetails/PrototypeDetailsInterface.php, Classes/Domain/PrototypeDetails/UseCases/UseCase.php, Classes/Domain/PrototypeDetails/UseCases/UseCaseCollection.php
enable it to override it like:
```yaml
Sitegeist\Monocle\Domain\PrototypeDetails\PrototypeDetailsFactoryInterface:
className: Foo\Bar\MyFactory
```
Extension point for https://github.com/sitegeist/Sitegeist.Monocle.PresentationObjects/pull/1
...
Description is WIP will add some more details later
=> Feature: ExtensionPoint PrototypeDetailsFactory

Classes/Aspects/FusionCachingAspect.php, Classes/Domain/Fusion/PrototypeRepository.php, Classes/Fusion/FusionService.php, Classes/Fusion/FusionView.php
Adjust to interface changes from https://github.com/neos/neos-development-collection/pull/4425
=> TASK: Adjust to interface changes from neosPr:4425

Classes/Package.php
If the new https://github.com/neos/neos-development-collection/pull/3903 is used to work with Monocle Components in the NodeTypes directory, this Fusion files need to be flushed too.
=> Flush `include: nodetypes://` file caches too

Configuration/Settings.yaml
Without this change it is not possible to run Monocle in a setup without database. Useful for frontend-only developers and automatic tests
=> BUGFIX: Make Monocle work without a database setup
